services:
  - type: web
    name: rouss-bot-web
    env: docker
    plan: free
    repo: https://github.com/AADiSanto/Rouss_Bot_Goggle_Sheets_Whatsapp
    branch: main
    startCommand: 'gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT'

  - type: worker
    name: rouss-bot-worker
    env: docker
    plan: free
    repo: https://github.com/AADiSanto/Rouss_Bot_Goggle_Sheets_Whatsapp
    branch: main
    startCommand: 'python worker.py'
